            - name: Eco CI Activity Checker
  # You may pin to the exact commit or the version.
  # uses: green-coding-solutions/eco-ci-activity-checker@3ddd5fcef7737a9db1c4779b749a948c45d1b295
  uses: green-coding-solutions/eco-ci-activity-checker@v1.1
  with:
    # format: {repo-owner}/{repo-name}
    repo: # optional, default is ${{ github.repository }}
    # the branch to check
    branch: # optional, default is ${{ github.ref_name }}
    # personal access token with repo scope, if using with a private repository
    personal-access-token: # optional, default is ${{ github.token }}
    # the id of the workflow to check
    workflow-id: # optional
          
